### ISSUE TITLE
chromedriver  

### ISSUE THREAD

**Issue by myeghaneh** [mpakniat7/appointment_availability_check#1]
First of all, thank you for your time, it is very nice to see that you share your practical code with everyone

I could execute the code after the first steps of opening the account in Twilio and installing the package by pipe. I got message 

"Program started" 

but I also get this message which probably is related to  chromedriver  ( I am using Win10, 64b)

```
Traceback (most recent call last):
  File "appointment_availability_check.py", line 46, in <module>
    driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)
  File "C:\Users\moha\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\moha\anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\moha\anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

```

could you please let me know what should I do?

**Comment by myeghaneh** [comment]
BTW, i put 

```
chrome_driver_path = "C:\appointment_availability_check-main\chromedriver.exe"
```
is that correct?

**Comment by mpakniat7** [comment]
try this on line 46:
driver = webdriver.Chrome(r"C:\appointment_availability_check-main\chromedriver.exe", options=chrome_options)
Let us know if it worked.

**Comment by myeghaneh** [comment]
thank you, I did it in that way. 

```
while not is_time_available:

    chrome_driver_path = r"C:\appointment_availability_check-main\chromedriver.exe"
    chrome_options = Options()
    chrome_options.add_argument("--start-maximized")
    driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)

```
it goes to main website 

https://ir-appointment.visametric.com/de/appointment-form


after inserting our info, it says now 

```
Es ist kein Termin verfügbar.
```

**Comment by mpakniat7** [comment]
Ok, so first problem solved!
Well, apparently there is no available appointments at the moment. your code will check every 5 minutes and will inform you as soon as any appointment is available. Good luck.

**Comment by myeghaneh** [comment]
yes.  thank you, As far as I see it check only 1 time...
